<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItoTEPk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItoTEPk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerItoTEPk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerItoTEPk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerItoTEPk\App_KernelDevDebugContainer([
    'container.build_hash' => 'ItoTEPk',
    'container.build_id' => 'a53f38e8',
    'container.build_time' => 1645613110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerItoTEPk');
