<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCy05Fmu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCy05Fmu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCy05Fmu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCy05Fmu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCy05Fmu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cy05Fmu',
    'container.build_id' => '8217881e',
    'container.build_time' => 1645759133,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCy05Fmu');
