<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJtAVOrO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJtAVOrO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJtAVOrO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJtAVOrO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJtAVOrO\App_KernelDevDebugContainer([
    'container.build_hash' => 'JtAVOrO',
    'container.build_id' => '6d7d79c7',
    'container.build_time' => 1645510075,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJtAVOrO');
